### PR TITLE
Use uWebSocket

### PR DESCRIPTION
**Pull request by sairus2k**

### CODE REVIEW

**Comment by ai** [comment]
@sairus2k note, that you still have problem in Travis CI

**Comment by sairus2k** [comment]
The problem doesn't reproduce locally.

**Comment by ai** [comment]
OK, I will try to look on my machine. Maybe it is related to concurrency. Or to yarn lock?

**Comment by sairus2k** [comment]
@ai Probably, localhost on Travic-CI resolves to ipv6 address
This is the issue:
https://github.com/uWebSockets/uWebSockets/issues/342
Then it fails only for node version 6.10.2 with another error. I restarted build using close and reopen pull request and all tests passed.

**Comment by ai** [comment]
Great invastigation. Sorry, I stock on Autoprefixer 7 release :(

**Comment by ai** [comment]
Thanks. Whatis your Twitter and VK accounts for announce?

**Comment by sairus2k** [comment]
[https://vk.com/sairus2k](https://vk.com/sairus2k)

**Pull request merged**
