### PR TITLE
Better reporter

### PR DESCRIPTION
**Pull request by okonet**
This is how it will look after the merge:

2016-11-14 at 12 36

but it's much easier to set up now by tweaking constants.

### CODE REVIEW

**Comment by okonet** [comment]
@ai I think this is solid and can be merged now. Thoughts?

**Comment by ai** [comment]
Sure, I like latest style.

Could you fix Travis (maybe you need to update server snapshots too, same `./test/servers/update.js` way)?

**Comment by okonet** [comment]
I was wondering why the build is failing. Just did that and tests are now green locally.

**Comment by ai** [comment]
Awesome. I will merge it tonight (my open source time is after the main work). Thanks for your work!

**Pull request merged**
